package gov.pcc.pwc.service.genSerialNumber.enums;

public enum SequenceNameEnum {
    REC_SEQ("REC_SEQ"),

    REV_SEQ("REV_SEQ"),

    ENG_ENGR_CERTIFICATE_ID_SEQ("ENG_ENGR_CERTIFICATE_ID_SEQ"),
    ENG_ENGR_SUBJECTPOINT_ID_SEQ("ENG_ENGR_SUBJECTPOINT_ID_SEQ"),

    ENG_COMP_SEQ("ENG_COMP_SEQ"),
    ENG_MEMBER_SEQ("ENG_MEMBER_SEQ"),
    ENG_CST_LICENCE_NO_SEQ("ENG_CST_LICENCE_NO_SEQ"),
    ENG_ENGR_CERTIFICATE_NO_SEQ("ENG_ENGR_CERTIFICATE_NO_SEQ"),
    ENG_ENGR_LICENCE_NO_SEQ("ENG_ENGR_LICENCE_NO_SEQ"),
    ENG_COURSE_SEQ("ENG_COURSE_SEQ"),
    ENG_TEACHER_SEQ("ENG_TEACHER_SEQ"),
    ENG_REVIEW_LOG_SEQ("ENG_REVIEW_LOG_SEQ"),

    ENG_ENGR_CERTIFICATE_DOC_NO_SEQ("ENG_ENGR_CERTIFICATE_DOC_NO_SEQ"),
    ENG_ENGR_LICENCE_DOC_NO_SEQ("ENG_ENGR_LICENCE_DOC_NO_SEQ"),
    ENG_CST_LICENCE_DOC_NO_SEQ("ENG_CST_LICENCE_DOC_NO_SEQ"),
    ENG_EBILLING_CHECK_SEQ("ENG_EBILLING_CHECK_SEQ"),

    INS_DUCON_OVERSEE("INS_DUCON_OVERSEE"),
    INS_DUCON_1999("INS_DUCON_1999"),

    FA1_IDLE_UTILITY("FA1_IDLE_UTILITY"),
    FA1_IDLE_OVERSEE_TEMP("FA1_IDLE_OVERSEE_TEMP"),
    FA1_IDLE_OVERSEE("FA1_IDLE_OVERSEE"),

    PRO_INNOVATIVE_PRODUCT("PRO_INNOVATIVE_PRODUCT_SEQ"),

    FA2_IDLE_PLNBAS("FA2_IDLE_PLNBAS"),

    QUA_QTRAIN_QTYCLASS("QUA_QTRAIN_QTYCLASS"),

    ALL_API_CALL_NO("ALL_API_CALL_NO");

    private final String seqName;

    SequenceNameEnum(String seqName) {
        this.seqName = seqName;
    }

    public String getSeqName() {
        return seqName;
    }
}
